FROM python:3.11-slim

WORKDIR /workspace

# Evita escribir __pycache__ en la carpeta montada del proyecto
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8050

CMD ["python", "app.py"]
