name: screen-time-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - nodejs
  - pip:
      - jupyter-book
